def failedfile():
    print("a")
    print("b")
    print("c")
    print("d")
    print("e")
    print("f")
    print("g")
    print("h")
    print("i")
    print("j")
    print("k")
    print("l")
    print("m")
    print("n")
    print("o")
    print("p")
    print("q")
    print("r")
    print("s")
    print("t")
    print("u")
    print("v")
    print("w")
    print("x")
    print("y")
    print("z")
    for r in range(100):
        for i in range(100):
            for j in range(100):
                print(r, i, j)
failedfile()
